version: '1'
services:
  myapp:
    container_name: discordbot
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9001:9001
    volumes:
      - ./:/discordbot/dev
      - ignore:/discordbot/dev/node_modules/
volumes:
  ignore: