version: '1'
services:
  discordbot:
    container_name: jeeves-bot
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9001:9001
    volumes:
      - ./:/discordbot/dev
      - ignore:/discordbot/dev/node_modules/

  mysql:
    container_name: mysql
    build:
      dockerfile: DockerfileDb
      context: .
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"

volumes:
  ignore: